version: "3.9"

services:
  db:
    image: mongo:jammy
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
    - ./:/db/:data/db
    ports:
    - 27017:27017